return {
  --- Inspired by <https://help.obsidian.md/callouts#Supported+types>
  keywords = {
    NOTE = { icon = "󰲶", color = "NOTE" },
    ABSTRACT = { icon = "󰨸", color = "ABSTRACT", alt = { "SUMMARY", "TLDR" } },
    INFO = { icon = "󰋽", color = "INFO" },
    TODO = { icon = "󰗡", color = "TODO" },
    TIP = { icon = "󰈸", color = "TIP", alt = { "HINT", "IMPORTANT", "SEE" } },
    SUCCESS = { icon = "󰄬", color = "SUCCESS", alt = { "CHECK", "DONE" } },
    QUESTION = { icon = "󰘥", color = "QUESTION", alt = { "FAQ", "HELP" } },
    WARNING = { icon = "󰀪", color = "WARNING", alt = { "ATTENTION", "CAUTION", "WARN" } },
    FAILURE = { icon = "󰅖", color = "FAILURE", alt = { "ERROR", "FAIL" } },
    DANGER = { icon = "󱐌", color = "DANGER", alt = { "HACK", "MISSING", "XXX" } },
    BUG = { icon = "󰨰", color = "BUG", alt = { "FIX", "FIXIT", "FIXME", "ISSUE" } },
    EXAMPLE = { icon = "󰉹", color = "EXAMPLE" },
    QUOTE = { icon = "󱆨", color = "QUOTE", alt = { "CITE" } },
    TEST = { icon = "󰂖", color = "TEST", alt = { "FAILED", "PASSED", "TESTING" } },
    PERF = { icon = "󰅒", color = "PERF", alt = { "OPTIM", "OPTIMIZE", "PERFORMANCE" } },
  },

  colors = {
    NOTE = "DiagnosticInfo",
    ABSTRACT = "DiagnosticOk",
    INFO = "DiagnosticInfo",
    TODO = "DiagnosticInfo",
    TIP = "DiagnosticOk",
    SUCCESS = "DiagnosticHint",
    QUESTION = "DiagnosticWarn",
    WARNING = "DiagnosticWarn",
    FAILURE = "DiagnosticError",
    DANGER = "DiagnosticError",
    BUG = "DiagnosticError",
    EXAMPLE = "Purple",
    QUOTE = "DiagnosticUnnecessary",
    TEST = "DiagnosticOk",
    PERF = "DiagnosticOk",
  },
}
